---
title: "La evolución del empleo a nivel global desde el punto de vista de género ################ en Argentina"
author: "Marianela Pi y Patricia Perrone"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Cargar los paquetes necesarios acá
library(usethis)
library(readr)
library(readxl)
library(ggplot2)
library(dplyr)
library(tidyr)
```


## Introducción

Corte en Argentina
Posible comparación con la región

## Exploración de los datos


```{r}
# Código para cargar o leer los datos
empleo_genero <- read.csv("datos/empleo_genero.csv") %>% filter(pais_region=="Argentina") %>% select(1,16:52)
# Eliminamos las columnas de años que no tiene datos para simplificar el análisis
```
```{r}
# Visualizo la nueva tabla
empleo_genero
```
```{r}
empleo_Arg <- pivot_longer(empleo_genero, cols=2:38, names_to = "Anio", values_to = "cantidad")
```
```{r}
print(empleo_Arg,n = 30)
```


```{r}
# comparación del desempleo por género

```



```{r}
# Cödigo de R acá 
# Agregá más bloques según sea necesario
```



## Hipótesis


## Conclusiones






